import { ShootingDay } from '../types'
import {
  SHOOTING_INFO_LABELS,
  formatTimelineTime,
  shootingTimelineTypeLabel,
  sortTimelineItems,
} from './shooting'

const WIDTH = 1600
const MARGIN = 48
const GRID = '#9ca3af'
const DARK = '#111827'
const MID = '#e5e7eb'
const LIGHT = '#f9fafb'
const TEXT = '#111827'
const MUTED = '#4b5563'

interface Column {
  label: string
  width: number
  align?: CanvasTextAlign
}

type Row = string[]

export function downloadCallSheetImage(day: ShootingDay, projectTitle = '') {
  const canvas = document.createElement('canvas')
  const measure = canvas.getContext('2d')
  if (!measure) return

  const sceneColumns: Column[] = [
    { label: 'S#', width: 78, align: 'center' },
    { label: '촬영 장소', width: 230 },
    { label: 'S/O/L', width: 92, align: 'center' },
    { label: 'D/N', width: 70, align: 'center' },
    { label: 'I/O', width: 70, align: 'center' },
    { label: '촬영 시간', width: 180, align: 'center' },
    { label: '컷 수', width: 70, align: 'center' },
    { label: '내용', width: 470 },
    { label: '등장인물', width: 250 },
  ]
  const sceneRows: Row[] =
    day.scenes.length > 0
      ? day.scenes.map((scene) => [
          scene.sceneNo || '-',
          scene.location || '-',
          scene.sol || '-',
          scene.dayNight || '-',
          scene.inOut || '-',
          scene.time || '-',
          scene.cutCount > 0 ? String(scene.cutCount) : '-',
          scene.description || '-',
          scene.cast || '-',
        ])
      : [['-', '-', '-', '-', '-', '-', '-', '씬 항목 미입력', '-']]

  const timelineColumns: Column[] = [
    { label: '시간', width: 220, align: 'center' },
    { label: '구분', width: 110, align: 'center' },
    { label: '내용', width: 820 },
    { label: '비고', width: 300 },
  ]
  const timelineRows: Row[] =
    day.timeline.length > 0
      ? sortTimelineItems(day.timeline).map((item) => [
          formatTimelineTime(item),
          shootingTimelineTypeLabel(item.type),
          item.content || '-',
          item.note || '-',
        ])
      : [['-', '-', '타임테이블 미입력', '-']]

  const infoColumns: Column[] = [
    { label: '구분', width: 160, align: 'center' },
    { label: '역할 / 장소 / 식사', width: 300 },
    { label: '이름 / 주소 / 업체', width: 500 },
    { label: '연락처 / 시간', width: 250 },
    { label: '비고', width: 240 },
  ]
  const infoRows: Row[] =
    day.info.length > 0
      ? day.info.map((item) => [
          SHOOTING_INFO_LABELS[item.type] || item.type,
          item.label || '-',
          item.name || '-',
          item.contact || '-',
          item.note || '-',
        ])
      : [['-', '-', '현장 정보 미입력', '-', '-']]

  const contentWidth = WIDTH - MARGIN * 2
  const titleHeight = 148
  const metaHeight = 184
  const sceneHeight = tableHeight(measure, sceneColumns, sceneRows)
  const timelineHeight = tableHeight(measure, timelineColumns, timelineRows)
  const infoHeight = tableHeight(measure, infoColumns, infoRows)
  const notesHeight = Math.max(76, wrapLines(measure, day.notes || '-', contentWidth - 32, '24px sans-serif').length * 32 + 44)
  const totalHeight =
    MARGIN +
    titleHeight +
    metaHeight +
    44 +
    sceneHeight +
    44 +
    timelineHeight +
    44 +
    infoHeight +
    44 +
    notesHeight +
    64

  canvas.width = WIDTH
  canvas.height = totalHeight
  const ctx = canvas.getContext('2d')
  if (!ctx) return

  ctx.fillStyle = '#ffffff'
  ctx.fillRect(0, 0, canvas.width, canvas.height)

  let y = MARGIN
  y = drawHeader(ctx, y, day, projectTitle)
  y = drawMeta(ctx, y, day)
  y += 28
  y = drawSectionTitle(ctx, y, '씬별 촬영표')
  y = drawTable(ctx, y, sceneColumns, sceneRows)
  y += 28
  y = drawSectionTitle(ctx, y, 'Time Table')
  y = drawTable(ctx, y, timelineColumns, timelineRows)
  y += 28
  y = drawSectionTitle(ctx, y, '현장 정보')
  y = drawTable(ctx, y, infoColumns, infoRows)
  y += 28
  y = drawSectionTitle(ctx, y, '오늘의 한마디 / 공지')
  y = drawNoteBox(ctx, y, day.notes || '-')

  ctx.font = '20px Pretendard, "Apple SD Gothic Neo", sans-serif'
  ctx.fillStyle = '#6b7280'
  ctx.fillText('Generated by Preprod Agent', MARGIN, y + 36)

  const filename = `${safeFilename(day.title || '일촬표')}.png`
  canvas.toBlob((blob) => {
    if (!blob) return
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }, 'image/png')
}

function drawHeader(
  ctx: CanvasRenderingContext2D,
  y: number,
  day: ShootingDay,
  projectTitle: string,
) {
  ctx.fillStyle = DARK
  ctx.fillRect(MARGIN, y, WIDTH - MARGIN * 2, 112)
  ctx.fillStyle = '#ffffff'
  ctx.font = '700 44px Pretendard, "Apple SD Gothic Neo", sans-serif'
  ctx.fillText('일일촬영계획표', MARGIN + 28, y + 48)
  ctx.font = '600 28px Pretendard, "Apple SD Gothic Neo", sans-serif'
  ctx.textAlign = 'right'
  ctx.fillText(day.title || 'DAY', WIDTH - MARGIN - 28, y + 48)
  ctx.font = '22px Pretendard, "Apple SD Gothic Neo", sans-serif'
  ctx.fillStyle = '#d1d5db'
  ctx.fillText(day.date || '촬영일 미입력', WIDTH - MARGIN - 28, y + 82)
  ctx.textAlign = 'left'
  if (projectTitle) {
    ctx.fillText(projectTitle, MARGIN + 28, y + 82)
  }
  return y + 132
}

function drawMeta(ctx: CanvasRenderingContext2D, y: number, day: ShootingDay) {
  const rows: Row[] = [
    ['예상날씨', joinMeta(day.weather, day.lowTemp, day.highTemp, day.rainChance), '집합 / 콜타임', day.callTime || '-'],
    ['일출 / 일몰', joinMeta(day.sunrise, day.sunset), '촬영 종료 / 복귀', day.wrapTime || '-'],
    ['베이스 / 집합 장소', day.basecamp || '-', '씬 / 시간표', `씬 ${day.scenes.length} · 시간표 ${day.timeline.length}`],
  ]
  const columns: Column[] = [
    { label: '항목', width: 210 },
    { label: '내용', width: 520 },
    { label: '항목', width: 210 },
    { label: '내용', width: 510 },
  ]
  return drawTable(ctx, y, columns, rows, { compact: true })
}

function drawSectionTitle(ctx: CanvasRenderingContext2D, y: number, title: string) {
  ctx.fillStyle = DARK
  ctx.fillRect(MARGIN, y, WIDTH - MARGIN * 2, 46)
  ctx.fillStyle = '#ffffff'
  ctx.font = '700 24px Pretendard, "Apple SD Gothic Neo", sans-serif'
  ctx.fillText(title, MARGIN + 18, y + 31)
  return y + 46
}

function drawTable(
  ctx: CanvasRenderingContext2D,
  y: number,
  columns: Column[],
  rows: Row[],
  options: { compact?: boolean } = {},
) {
  const x = MARGIN
  const headerHeight = options.compact ? 0 : 42
  const bodyFont = options.compact
    ? '23px Pretendard, "Apple SD Gothic Neo", sans-serif'
    : '22px Pretendard, "Apple SD Gothic Neo", sans-serif'
  let cy = y

  if (!options.compact) {
    ctx.fillStyle = MID
    ctx.fillRect(x, cy, columnsWidth(columns), headerHeight)
    let cx = x
    for (const column of columns) {
      drawCellBorder(ctx, cx, cy, column.width, headerHeight)
      drawText(ctx, column.label, cx + 10, cy + 27, column.width - 20, {
        font: '700 20px Pretendard, "Apple SD Gothic Neo", sans-serif',
        color: TEXT,
        align: column.align,
      })
      cx += column.width
    }
    cy += headerHeight
  }

  rows.forEach((row, rowIndex) => {
    const h = rowHeight(ctx, columns, row, bodyFont, options.compact ? 42 : 48)
    ctx.fillStyle = options.compact && rowIndex % 2 === 0 ? LIGHT : '#ffffff'
    ctx.fillRect(x, cy, columnsWidth(columns), h)
    let cx = x
    row.forEach((value, idx) => {
      const column = columns[idx]
      drawCellBorder(ctx, cx, cy, column.width, h)
      drawText(ctx, value, cx + 10, cy + 28, column.width - 20, {
        font: bodyFont,
        color: idx % 2 === 0 && options.compact ? MUTED : TEXT,
        align: column.align,
      })
      cx += column.width
    })
    cy += h
  })

  return cy
}

function drawNoteBox(ctx: CanvasRenderingContext2D, y: number, value: string) {
  const width = WIDTH - MARGIN * 2
  const lines = wrapLines(
    ctx,
    value,
    width - 32,
    '24px Pretendard, "Apple SD Gothic Neo", sans-serif',
  )
  const h = Math.max(76, lines.length * 32 + 44)
  ctx.fillStyle = LIGHT
  ctx.fillRect(MARGIN, y, width, h)
  drawCellBorder(ctx, MARGIN, y, width, h)
  ctx.font = '24px Pretendard, "Apple SD Gothic Neo", sans-serif'
  ctx.fillStyle = TEXT
  lines.forEach((line, idx) => ctx.fillText(line, MARGIN + 16, y + 34 + idx * 32))
  return y + h
}

function drawCellBorder(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
) {
  ctx.strokeStyle = GRID
  ctx.lineWidth = 1
  ctx.strokeRect(x, y, width, height)
}

function drawText(
  ctx: CanvasRenderingContext2D,
  value: string,
  x: number,
  y: number,
  width: number,
  options: {
    font: string
    color: string
    align?: CanvasTextAlign
  },
) {
  ctx.font = options.font
  ctx.fillStyle = options.color
  ctx.textAlign = options.align ?? 'left'
  const lines = wrapLines(ctx, value || '-', width, options.font)
  const tx = options.align === 'center' ? x + width / 2 : x
  lines.slice(0, 4).forEach((line, idx) => ctx.fillText(line, tx, y + idx * 26))
  ctx.textAlign = 'left'
}

function tableHeight(ctx: CanvasRenderingContext2D, columns: Column[], rows: Row[]) {
  return 42 + rows.reduce((sum, row) => sum + rowHeight(ctx, columns, row), 0)
}

function rowHeight(
  ctx: CanvasRenderingContext2D,
  columns: Column[],
  row: Row,
  font = '22px sans-serif',
  minHeight = 48,
) {
  const lineCounts = row.map((value, idx) =>
    wrapLines(ctx, value, columns[idx].width - 20, font).length,
  )
  return Math.max(minHeight, Math.min(4, Math.max(...lineCounts)) * 28 + 18)
}

function wrapLines(
  ctx: CanvasRenderingContext2D,
  value: string,
  width: number,
  font: string,
) {
  ctx.font = font
  const text = String(value || '-')
  const words = text
    .replace(/\n/g, ' \n ')
    .split(/\s+/)
    .filter((word) => word.length > 0)
  const lines: string[] = []
  let current = ''

  words.forEach((word) => {
    if (word === '\n') {
      lines.push(current)
      current = ''
      return
    }
    const next = current ? `${current} ${word}` : word
    if (ctx.measureText(next).width <= width) {
      current = next
      return
    }
    if (current) lines.push(current)
    if (ctx.measureText(word).width <= width) {
      current = word
      return
    }
    const chars = [...word]
    current = ''
    chars.forEach((char) => {
      const nextChar = current + char
      if (ctx.measureText(nextChar).width <= width) {
        current = nextChar
        return
      }
      if (current) lines.push(current)
      current = char
    })
  })
  if (current) lines.push(current)
  return lines.length > 0 ? lines : ['-']
}

function columnsWidth(columns: Column[]) {
  return columns.reduce((sum, column) => sum + column.width, 0)
}

function joinMeta(...values: string[]) {
  return values.filter(Boolean).join(' / ') || '-'
}

function safeFilename(value: string) {
  return value.replace(/[\\/:*?"<>|]/g, '_')
}
