import {
  AppState,
  ChecklistCategory,
  ChecklistItem,
  ChecklistStatus,
} from './types'

const nextId = (() => {
  let n = 0
  return () => `seed-${++n}`
})()

const item = (
  category: ChecklistCategory,
  title: string,
  status: ChecklistStatus = 'todo',
  note = '',
): ChecklistItem => ({
  id: nextId(),
  category,
  title,
  status,
  note,
})

export const SEED: AppState = {
  project: {
    title: '',
    format: '',
    genre: '',
    runtime: 0,
    logline: '',
    shootStartDate: '',
    shootEndDate: '',
    mainLocations: [],
    productionScale: '',
    director: '',
    producer: '',
  },
  crew: [],
  checklist: [
    item('기획', '프로젝트 개요 확정'),
    item('기획', '기획의도 / 목표 정리'),
    item('기획', '제작 일정 기준 설정'),
    item('스태프/계약', '스태프 역할 / 연락망 정리'),
    item('스태프/계약', '페이 / 계약 / 정산 조건 확인'),
    item('스태프/계약', '공지 채널 / 승인 라인 정리'),
    item('시나리오', '시나리오 / 구성안 확정'),
    item('시나리오', '씬 리스트 / 컷 플로우 정리'),
    item('시나리오', '콘티 / continuity 초안 작성'),
    item('캐스팅', '주요 출연자 / 모델 후보 정리'),
    item('캐스팅', '출연자 일정 확인'),
    item('캐스팅', '계약 / 초상권 / 동의서 확인'),
    item('로케이션', '주요 로케이션 후보 정리'),
    item('로케이션', '답사 / 사진 자료 확보'),
    item('로케이션', '촬영 허가 / 사용 조건 확인'),
    item('미술/의상', '아트 / 소품 방향 정리'),
    item('미술/의상', '의상 / 스타일링 방향 정리'),
    item('미술/의상', '구매 / 제작 / 렌탈 목록 작성'),
    item('촬영/조명', '카메라 / 렌즈 패키지 결정'),
    item('촬영/조명', '조명 장비 / 전력 조건 확인'),
    item('촬영/조명', '촬영 테스트 / 레퍼런스 확인'),
    item('사운드', '동시녹음 필요 범위 확인'),
    item('사운드', '마이크 / 녹음 장비 확인'),
    item('제작/예산', '전체 예산 프레임 작성'),
    item('제작/예산', '인건비 / 장비 / 로케이션 견적 입력'),
    item('제작/예산', '식대 / 이동 / 숙박 운영안 작성'),
    item('제작/예산', '예비비 / 변동비 기준 설정'),
    item('스케줄', '촬영 회차표 작성'),
    item('스케줄', '리허설 / 테스트 일정 확인'),
    item('스케줄', '콜타임 / 이동 / 식사 계획 정리'),
    item('데이터/후반', '메모리 카드 / 백업 플로우 정리'),
    item('데이터/후반', '후반 작업 범위 / 담당자 확인'),
    item('데이터/후반', '납품 포맷 / 마감 기준 확인'),
    item('안전/허가', '현장 안전 체크리스트 작성'),
    item('안전/허가', '보험 / 동의서 / 허가서 확인'),
    item('안전/허가', '비상 연락망 / 대체 플랜 정리'),
  ],
  documents: {
    intention: '',
    directing: '',
    toneAndManner: '',
    references: '',
    storyboard: '',
    productionPlan: '',
    shootingStrategy: '',
    castingStyling: '',
    artCostume: '',
    locationNote: '',
    propsEquipment: '',
    schedulePlan: '',
    meetingNotes: '',
    riskMemo: '',
    meetingAgenda: '',
  },
  meetingLogs: [],
  shootingDays: [],
  budget: [],
  assets: [],
  updatedAt: new Date().toISOString(),
}
